### ISSUE TITLE
add URLs to package metadata

### ISSUE THREAD

**Issue by ntessore** [euclidlib/euclidlib#3]
We should add a couple of useful URLs to `pyproject.toml`, so that they show up as links on the [PyPI page](https://pypi.org/p/euclidlib).

For the time being, we could add:

```toml
[project.urls]
Repository = "https://github.com/euclidlib/euclidlib"
Issues = "https://github.com/euclidlib/euclidlib/issues"
```
